// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/tx7do/go-wind-admin-template/app/admin/service/internal/data"
	"github.com/tx7do/go-wind-admin-template/app/admin/service/internal/server"
	"github.com/tx7do/go-wind-admin-template/app/admin/service/internal/service"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
)

// Injectors from wire.go:

// initApp 初始化 kratos 应用的 Wire provider 入口。
// initApp initializes the Wire provider entry for the kratos application.
//
// 参数 / Parameters:
//   - *bootstrap.Context: 引导上下文 / *bootstrap.Context: bootstrap context
//
// 返回 / Returns:
//   - *kratos.App: 已构建的应用实例 / *kratos.App: constructed application instance
//   - func(): 应用关闭时的清理函数 / func(): cleanup function to run on shutdown
//   - error: 构建过程中可能发生的错误 / error: possible construction error
func initApp(context *bootstrap.Context) (*kratos.App, func(), error) {
	restMiddlewares := server.NewRestMiddleware(context)
	greeterRepo := data.NewGreeterRepo(context)
	greeterService := service.NewGreeterService(context, greeterRepo)
	httpServer := server.NewRestServer(context, restMiddlewares, greeterService)
	grpcMiddlewares := server.NewGrpcMiddleware(context)
	grpcServer := server.NewGrpcServer(context, grpcMiddlewares, greeterService)
	app := newApp(context, httpServer, grpcServer)
	return app, func() {
	}, nil
}
